### ISSUE TITLE
After training the model how do i use it?

### ISSUE THREAD

**Issue by saxobroko** [yatharthgarg/Speech-Accent-Recognition#5]
How do i use the model to get the result?

**Comment by saxobroko** [comment]
Before we do that though i'm getting this error during training.
```
Converting to MFCC....
Traceback (most recent call last):
  File "trainmodel.py", line 264, in <module>
    X_train, _, y_train, _ = train_test_split(X_train, y_train, test_size=0)
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\sklearn\model_selection\_split.py", line 2130, in train_test_split
    n_train, n_test = _validate_shuffle_split(n_samples, test_size, train_size,
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\sklearn\model_selection\_split.py", line 1764, in _validate_shuffle_split
    raise ValueError('test_size={0} should be either positive and smaller'
ValueError: test_size=0 should be either positive and smaller than the number of samples 41605 or a float in the (0, 1) range
```
